minor semplification, add branch print and creation functions

diff --git a/bin/git-rflow b/bin/git-rflow
--- a/bin/git-rflow
+++ b/bin/git-rflow
@@ -4,7 +4,6 @@
 REMOTE=`git config --get rflow.remote`
 DEVELOPMENT_BRANCH=`git config --get rflow.branch.development`
 PRODUCTION_BRANCH=`git config --get rflow.branch.production`
-CFG_PIPELINE=`git config --get rflow.pipeline`
 
 # apply defaults
 REMOTE=${REMOTE:-origin}
@@ -12,23 +11,17 @@ DEVELOPMENT_BRANCH=${DEVELOPMENT_BRANCH:-develop}
 PRODUCTION_BRANCH=${PRODUCTION_BRANCH:-master}
 DEVELOPMENT_BRANCH_PREFIX=${DEVELOPMENT_BRANCH_PREFIX:-feature}
 PRODUCTION_BRANCH_PREFIX=${PRODUCTION_BRANCH_PREFIX:-hotfix}
-CFG_PIPELINE=${CFG_PIPELINE:-hotfix:master;feature:develop}
 
-# build the pipeline array from the configuration
-declare -A PIPELINE
-for stage in ${CFG_PIPELINE/;/ }
-do
-  splitted_stage=( ${stage/:/ } )
-  PIPELINE[${splitted_stage[1]}]=${splitted_stage[0]}
-done
-unset splitted_stage
-
+# define output colors
 RED=`tput setaf 1`
 GREEN=`tput setaf 2`
 YELLOW=`tput setaf 3`
 BLUE=`tput setaf 4`
 NO_COLOR=`tput sgr0`
 
+declare -A PIPELINE=( ["${DEVELOPMENT_BRANCH_PREFIX}"]="${DEVELOPMENT_BRANCH}" ["${PRODUCTION_BRANCH_PREFIX}"]="${PRODUCTION_BRANCH}" )
+
+# define print functions
 function warning()
 {
   echo "${YELLOW}Warning: $@${NO_COLOR}"
@@ -41,7 +34,7 @@ function error()
 
 function info()
 {
-  echo "${BLUE}>>> $@${NO_COLOR}"
+  echo "${BLUE}> $@${NO_COLOR}"
 }
 
 function success()
@@ -53,20 +46,51 @@ function success()
   echo ${NO_COLOR}
 }
 
+## list all the remote branches of the given type
+##
+## $1 the type of branches to list, expressed using one of the configured prefixes
+##
+function list_remote_branches()
+{
+  local branch_type=$1
+
+  git for-each-ref --format='%(refname)' refs/remotes/${REMOTE}/${branch_type} | sed -e "s:^refs/remotes/${REMOTE}/${branch_type}/::"
+}
+
+## list all the local branches of the given type
+##
+## $1 the type of branches to list, expressed using one of the configured prefixes
+##
+function list_local_branches()
+{
+  git for-each-ref --format='%(refname)' refs/heads/${branch_type} | sed -e "s:^refs/heads/${branch_type}/::"
+}
+
+## list all the local and remote branches of the given type
+##
+## $1 the type of branches to list, expressed using one of the configured prefixes
+##
+function list_branches()
+{
+  local branch_type=$1
+
+  { list_remote_branches ${branch_type}; list_local_branches ${branch_type}; } | sort -u
+}
+
 ## check if the given branch is a pipeline branch
 ##
-## @param $1 the branch to check
+## $1 the branch to check
 ##
 function is_pipeline_branch()
 {
   local branch=$1
 
-  [[ ${branch} == ${PRODUCTION_BRANCH} || ${branch} == ${DEVELOPMENT_BRANCH} ]] && return 0 || return 1
+  [[ ${branch} == ${PRODUCTION_BRANCH} || ${branch} == ${DEVELOPMENT_BRANCH} ]]
 }
 
 ## normalize the given branch name by prepending the branch type name, if missing
 ##
-## @param $1 the branch name to normalize
+## $1 the branch name to normalize
 ##
 function normalize_branch_name()
 {
@@ -84,16 +108,16 @@ function normalize_branch_name()
 
 ## validate the given branch merge operation by validating the user input
 ##
-## @param $1 the branch that will be merged
-## @param $2 the branch that the first argument will be merged into
-## @param $3 the branch prefix accepted by the target branch
+## $1 the branch that will be merged
+## $2 the branch that the first argument will be merged into
+## $3 the branch prefix accepted by the target branch
 ##
 function branch_merge_validate()
 {
   local source_branch=$1
   local target_branch=$2
-  local target_branch_prefix=$3
-  local normalized_source_branch=`normalize_branch_name "${source_branch}" "${target_branch_prefix}"`
+  local branch_type=$3
+  local normalized_source_branch=`normalize_branch_name "${source_branch}" "${branch_type}"`
 
   [[ "${source_branch}" == "${target_branch}" ]] && warning "are you trying to merge '${target_branch}' into itself?"
 
@@ -103,80 +127,139 @@ function branch_merge_validate()
   fi
 
   [[ -z "${normalized_source_branch}" ]] && error "expecting branch name" && exit 1
-  git show-ref --verify --quiet "refs/remotes/${REMOTE}/${normalized_source_branch}" || { error "invalid branch '${normalized_source_branch}'"; exit 1; }
+
+  if ! git show-ref --verify --quiet "refs/remotes/${REMOTE}/${normalized_source_branch}"
+  then
+    error "invalid branch '${normalized_source_branch}'"
+    exit 1
+  fi
 }
 
+## merge a branch into another and recursively rebase all the branches of the same type on the
+##
+## $1 the branch that will be rebased
+## $2 the type of the branch
+##
 function branch_merge()
 {
-  local source_branch=$1
-  local target_branch=$2
-  local source_branch_prefix=$3
-  local rebase_target_branch=`is_pipeline_branch "${source_branch}" && echo ${REMOTE}/`${target_branch}
+  local branch=$1
+  local branch_type=$2
+  local pipeline_branch=${PIPELINE["${branch_type}"]}
 
-  info "rebasing branch '${source_branch}' on '${target_branch}'"
+  info "rebasing pipeline branch '${pipeline_branch}' on '${branch}'"
 
-  # 1. rebase source_branch on the selected branch
-  # 2. rebase each branch forked from source_branch on the just updated source_branch
+  # 1. rebase pipeline_branch on the selected branch
+  # 2. rebase each branch forked from pipeline_branch on the just updated pipeline_branch
   # 3. remove the selected branch
 
-  git checkout ${source_branch} && \
-  git rebase ${rebase_target_branch} && \
-  rebase_all ${source_branch} ${source_branch_prefix} && \
-  [[ ${target_branch} != ${PRODUCTION_BRANCH} ]] && \
-  info "deleting merged branch '${target_branch}'" && \
-  git push --delete ${REMOTE} ${target_branch}
+  git checkout ${pipeline_branch} && \
+  git rebase ${REMOTE}/${branch} && \
+  resync_branches ${branch_type} && \
+  info "deleting merged branch '${branch}'" && \
+  git push --delete ${REMOTE} ${branch}
 }
 
-function rebase_all()
+## perform a multiple rebase of all the branches of the given type on their own pipeline branch
+##
+## $1 the type of branches that will be rebased on their own pipeline branch
+##
+function resync_branches()
 {
-  local source_branch=$1
-  local branch_type=$2
+  local branch_type=$1
   local branch
+  local pipeline_branch=${PIPELINE["${branch_type}"]}
 
-  for branch in `git for-each-ref --format='%(refname)' refs/remotes/${REMOTE}/${branch_type} | sed -e "s:^refs/remotes/${REMOTE}/::"`
+  for branch in `list_remote_branches ${branch_type}`
   do
-    info "rebasing ${branch} on ${source_branch}"
-    git checkout $branch && \
-    git rebase ${source_branch} && \
+    branch=${branch_type}/${branch}
+
+    # check preconditions
+    #if ! git merge-base --is-ancestor "${pipeline_branch}" "${branch}"
+    #then
+    #  error "branch '${branch}' is not an ancestor of '${pipeline_branch}'"
+    #fi
+
+    info "rebasing ${branch} on ${pipeline_branch}"
+    git checkout ${branch} && \
+    git rebase ${pipeline_branch} && \
     git push -f && \
-    git checkout ${source_branch} && \
+    git checkout ${pipeline_branch} && \
     git branch -D $branch
+    sleep 1
   done
 }
 
+## merge a feature branch into the development branch; this will recursiverly rebase all the feature branches on the
+## development branch
+##
+## $1 the feature branch name
+##
 function feature_merge()
 {
   local branch=$1
 
   branch_merge_validate ${branch} ${DEVELOPMENT_BRANCH} ${DEVELOPMENT_BRANCH_PREFIX} && \
-  branch_merge ${DEVELOPMENT_BRANCH} `normalize_branch_name "${branch}" "${DEVELOPMENT_BRANCH_PREFIX}"` ${DEVELOPMENT_BRANCH_PREFIX} && \
+  branch_merge `normalize_branch_name "${branch}" "${DEVELOPMENT_BRANCH_PREFIX}"` ${DEVELOPMENT_BRANCH_PREFIX} && \
   success "branch '${branch}' merged with '${DEVELOPMENT_BRANCH}'"
 }
 
+## merge a hotfix branch into the production branch; this will recursively rebase the development branch on the
+## production branch and all the feature branches on the latter
+##
+## $1 the hotfix branch name
+##
 function hotfix_merge()
 {
   local branch=$1
 
   branch_merge_validate ${branch} ${PRODUCTION_BRANCH} ${PRODUCTION_BRANCH_PREFIX} && \
-  branch_merge ${PRODUCTION_BRANCH} `normalize_branch_name "${branch}" "${PRODUCTION_BRANCH_PREFIX}"` ${PRODUCTION_BRANCH_PREFIX} && \
-  info "rebasing ${branch} on ${PRODUCTION_BRANCH}" && \
+  branch_merge `normalize_branch_name "${branch}" "${PRODUCTION_BRANCH_PREFIX}"` ${PRODUCTION_BRANCH_PREFIX} && \
+  info "rebasing ${DEVELOPMENT_BRANCH} on ${PRODUCTION_BRANCH}" && \
   git checkout ${DEVELOPMENT_BRANCH} && \
+  git rebase ${REMOTE}/${DEVELOPMENT_BRANCH} && \
   git rebase ${PRODUCTION_BRANCH} && \
-  rebase_all ${DEVELOPMENT_BRANCH} ${DEVELOPMENT_BRANCH_PREFIX} && \
+  resync_branches ${DEVELOPMENT_BRANCH_PREFIX} && \
   success "branch '${branch}' merged with '${DEVELOPMENT_BRANCH}'"
+}
+
+## open a new branch of the given type
+##
+## $1 the type of the branch
+## $2 the branch name
+##
+function branch_start()
+{
+  local branch_type=$1
+  local branch=$2
+
+  if [[ -n `list_branches ${branch_type} | grep ^${branch}$` ]]
+  then
+    error 'a branch with this name already exists' && exit 1
+  fi
+
+  if ! echo "${branch}" | grep -e '^[a-z0-9][a-z0-9-]*[a-z0-9]$' | grep -v -e '-\{2,\}'
+  then
+    error 'invalid branch name (tip: use kebab case)' && exit 1
+  fi
+
+  git checkout -b "${branch_type}/${branch}"
 }
 
 if [[ -z $@ ]]
 then
   cat << EOT
 Usage:
-  git rflow feature start <branch>
-  git rflow feature publish <branch>
-  git rflow feature merge <branch>
-  git rflow hotfix start <branch>
-  git rflow hotfix publish <branch>
-  git rflow hotfix merge <branch>
-  git rflow update
+  git rflow feature                    # list the feature branches
+  git rflow feature start <branch>     # create a feature branch
+  git rflow feature delete <branch>    # delete the feature branch
+  git rflow feature publish <branch>   # push the feature branch on the remote
+  git rflow feature merge <branch>     # merge the feature branch in the development branch
+  git rflow hotfix                     # list the hotfix branches
+  git rflow hotfix start <branch>      # create a hotfix branch
+  git rflow hotfix delete <branch>     # delete the hotfix branch
+  git rflow hotfix publish <branch>    # push the hotfix branch on the remote
+  git rflow hotfix merge <branch>      # merge the hotfix branch in the production branch
+  git rflow update                     # rebase every branch on the production branch
 EOT
 
   exit 0
@@ -187,7 +270,9 @@ case $1 in
     shift
 
     case $1 in
+      start) branch_start feature $2 ;;
       merge) feature_merge $2 ;;
+      '') list_branches feature ;;
       *) error "invalid argument '$1'" && exit 1 ;;
     esac
 
@@ -196,10 +281,15 @@ case $1 in
     shift
 
     case $1 in
+      start) branch_start hotfix $2 ;;
       merge) hotfix_merge $2 ;;
+      '') list_branches hotfix ;;
       *) error "invalid argument '$1'" && exit 1 ;;
     esac
 
+    ;;
+  update)
+    shift
     ;;
   *)
     error "invalid argument '$1'" && exit 1
